// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmFyHmYQYHDN-RBeThDODvIzkfgDRUkzg',
    appId: '1:536811926725:web:79ad2b9123fd22572eacac',
    messagingSenderId: '536811926725',
    projectId: 'chhat-app-7e66e',
    authDomain: 'chhat-app-7e66e.firebaseapp.com',
    storageBucket: 'chhat-app-7e66e.firebasestorage.app',
    measurementId: 'G-E32G0JRYSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ9UhsPs7MCcJp0subggBW5uYOQC9FTLI',
    appId: '1:536811926725:android:4adf8936bfa690812eacac',
    messagingSenderId: '536811926725',
    projectId: 'chhat-app-7e66e',
    storageBucket: 'chhat-app-7e66e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDip2XD4OCC2iLiLjGWJSdmrixktADY-4Q',
    appId: '1:536811926725:ios:29750509b64ee7892eacac',
    messagingSenderId: '536811926725',
    projectId: 'chhat-app-7e66e',
    storageBucket: 'chhat-app-7e66e.firebasestorage.app',
    iosBundleId: 'com.example.chhat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDip2XD4OCC2iLiLjGWJSdmrixktADY-4Q',
    appId: '1:536811926725:ios:29750509b64ee7892eacac',
    messagingSenderId: '536811926725',
    projectId: 'chhat-app-7e66e',
    storageBucket: 'chhat-app-7e66e.firebasestorage.app',
    iosBundleId: 'com.example.chhat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmFyHmYQYHDN-RBeThDODvIzkfgDRUkzg',
    appId: '1:536811926725:web:65ee85aab03192b52eacac',
    messagingSenderId: '536811926725',
    projectId: 'chhat-app-7e66e',
    authDomain: 'chhat-app-7e66e.firebaseapp.com',
    storageBucket: 'chhat-app-7e66e.firebasestorage.app',
    measurementId: 'G-PZG3B3FFYJ',
  );

}